name: Build Paper
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    if: >
      (
        (github.event_name == 'push')
        || (github.event_name == 'pull_request' && github.repository != github.event.pull_request.head.repo.full_name && contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action))
        || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'build-pr-jar')
      )

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Build
        uses: actions/github-script@v7
        id: determine
        env:
          REF_NAME: "${{ github.ref_name }}"
          REF_TYPE: "${{ github.ref_type }}"
          EVENT: "${{ toJSON(github.event) }}"
          EVENT_TYPE: "${{ github.event_name }}"
        with:
          script: |
            const {owner, repo} = context.repo;
            const event_name = `${process.env.EVENT_TYPE}`;
            const event = JSON.parse(`${process.env.EVENT}`);
            const ref_type = `${process.env.REF_TYPE}`;
            const ref_name = `${process.env.REF_NAME}`;
            const result = {
              action: "build"
            };

            if (event_name === "push" && ref_type === "branch") {
              const {data: pulls} = await github.rest.pulls.list({ owner, repo, head: `${owner}:${ref_name}`, state: "open" });
              const pull = pulls.find((pr) => !!pr.labels.find((l) => l.name === "build-pr-jar"));
              if (pull) {
                result["pr"] = pull.number;
                result["action"] = "paperclip";
                return result;
              }
            } else if (event_name === "pull_request" && event.pull_request.labels.find((l) => l.name === "build-pr-jar")) {
              result["pr"] = event.pull_request.number;
              result["action"] = "paperclip";
              return result;
            }
            return result;

      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (${{ matrix.java }})
          path: |
            **/build/test-results/test/TEST-*.xml

      - name: Create Paperclip Jar
        if: fromJSON(steps.determine.outputs.result).action == 'paperclip'
        run: |
          mkdir -p builds
          ./gradlew createMojmapPaperclipJar --stacktrace
          cp paper-server/build/libs/paper-paperclip-*-mojmap.jar builds/

      - name: Upload Paperclip Jar Artifact
        if: fromJSON(steps.determine.outputs.result).action == 'paperclip'
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{ fromJSON(steps.determine.outputs.result).pr }}
          path: builds/paper-paperclip-*-mojmap.jar

      - name: Release (Pre-release)
        if: fromJSON(steps.determine.outputs.result).action == 'paperclip'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "pr-${{ fromJSON(steps.determine.outputs.result).pr }}"
          name: "PR Build #${{ fromJSON(steps.determine.outputs.result).pr }}"
          prerelease: true
          files: builds/paper-paperclip-*-mojmap.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  event_file:
    name: "Event File"
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
